export const SET_PERSONAL_INFO='SET_PERSONAL_INFO';

export const SET_NUMBER_OF_WHEEL='SET_NUMBER_OF_WHEEL';

export const SET_VEHICLE_TYPE='SET_VEHICLE_TYPE';

export const SET_VEHICLE_MODEL='SET_VEHICLE_MODEL';

export const SET_DATE_RANGE='SET_DATE_RANGE';

export const SAVE_BOOKING_DETAILS='SAVE_BOOKING_DETAILS'